In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])

In [2]:
a

array([1, 2, 3, 4])

In [4]:
a.dtype

dtype('int32')

In [5]:
a.shape

(4,)

In [ ]:
a = np.empty((2, 3))

In [6]:
a

array([1, 2, 3, 4])

In [7]:
b = np.zeros( (2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
c = np.ones((2, 3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
e = np.full( (2, 3, 4), 255)
e

array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]]])

In [10]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [11]:
b = np.arange(3,9,2)
b

array([0, 1, 2, 3, 4])

In [12]:
c = np.random.rand(2,3)
c

array([[0.68951093, 0.13822422, 0.43819231],
       [0.94237077, 0.90396571, 0.45255318]])

In [13]:
d = np.random.randn()
d

0.0803358673351226

In [14]:
mylist = list(range(10))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
for i in range(len (mylist)):
    mylist[i] = mylist[i] + 1
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
a * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
a - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [21]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [22]:
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
b = np.arange(6).reshape(2, -1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
b * 2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [29]:
a = np.arange(10, 60, 10)
b = np.arange(1, 6)

In [30]:
a

array([10, 20, 30, 40, 50])

In [31]:
b

array([1, 2, 3, 4, 5])

In [32]:
a + b

array([11, 22, 33, 44, 55])

In [33]:
a - b

array([ 9, 18, 27, 36, 45])

In [34]:
a * b

array([ 10,  40,  90, 160, 250])

In [35]:
a / b

array([10., 10., 10., 10., 10.])

In [36]:
a ** b

array([       10,       400,     27000,   2560000, 312500000])

In [37]:
a = np.ones((2, 3))
b = np.ones((3, 2))
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a[5]

5

In [40]:
b = np.arange(12).reshape(3, 4)

In [41]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
b[1]

array([4, 5, 6, 7])

In [44]:
b[1, 2]

6

In [45]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[5]

5

In [47]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
b[0]

array([0, 1, 2, 3])

In [49]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
b[1,2] = 99

In [52]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a[2:5]

array([2, 3, 4])

In [55]:
a[5:]

array([5, 6, 7, 8, 9])

In [56]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b = np.arange(12).reshape(3, 4)

In [58]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
b[0:2, 1]

array([1, 5])

In [60]:
b[2, :]

array([ 8,  9, 10, 11])

In [61]:
b[:, 1]

array([1, 5, 9])

In [63]:
b[0:2, 1:3] = 0

In [64]:
b

array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [65]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])