In [1]:
import numpy as np
a = np.array([1, 2, 3, 4])

In [2]:
a

array([1, 2, 3, 4])

In [4]:
a.dtype

dtype('int32')

In [5]:
a.shape

(4,)

In [ ]:
a = np.empty((2, 3))

In [6]:
a

array([1, 2, 3, 4])

In [7]:
b = np.zeros( (2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
c = np.ones((2, 3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
e = np.full( (2, 3, 4), 255)
e

array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]]])

In [10]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [11]:
b = np.arange(3,9,2)
b

array([0, 1, 2, 3, 4])

In [12]:
c = np.random.rand(2,3)
c

array([[0.68951093, 0.13822422, 0.43819231],
       [0.94237077, 0.90396571, 0.45255318]])

In [13]:
d = np.random.randn()
d

0.0803358673351226

In [14]:
mylist = list(range(10))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
for i in range(len (mylist)):
    mylist[i] = mylist[i] + 1
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
a * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
a - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [21]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [22]:
a ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
b = np.arange(6).reshape(2, -1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
b * 2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [27]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [29]:
a = np.arange(10, 60, 10)
b = np.arange(1, 6)

In [30]:
a

array([10, 20, 30, 40, 50])

In [31]:
b

array([1, 2, 3, 4, 5])

In [32]:
a + b

array([11, 22, 33, 44, 55])

In [33]:
a - b

array([ 9, 18, 27, 36, 45])

In [34]:
a * b

array([ 10,  40,  90, 160, 250])

In [35]:
a / b

array([10., 10., 10., 10., 10.])

In [36]:
a ** b

array([       10,       400,     27000,   2560000, 312500000])

In [37]:
a = np.ones((2, 3))
b = np.ones((3, 2))
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a[5]

5

In [40]:
b = np.arange(12).reshape(3, 4)

In [41]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
b[1]

array([4, 5, 6, 7])

In [44]:
b[1, 2]

6

In [45]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[5]

5

In [47]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
b[0]

array([0, 1, 2, 3])

In [49]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
b[1,2] = 99

In [52]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5, 99,  7],
       [ 8,  9, 10, 11]])

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a[2:5]

array([2, 3, 4])

In [55]:
a[5:]

array([5, 6, 7, 8, 9])

In [56]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b = np.arange(12).reshape(3, 4)

In [58]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
b[0:2, 1]

array([1, 5])

In [60]:
b[2, :]

array([ 8,  9, 10, 11])

In [61]:
b[:, 1]

array([1, 5, 9])

In [63]:
b[0:2, 1:3] = 0

In [64]:
b

array([[ 0,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  9, 10, 11]])

In [65]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [66]:
a[[1, 3]]

array([1, 3])

In [67]:
a[[True, False, True, False, True]]

array([0, 2, 4])

In [68]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
b = a > 5

In [70]:
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [71]:
a[b]

array([6, 7, 8, 9])

In [72]:
a[a>5]

array([6, 7, 8, 9])

In [73]:
a[a>5] = 1
a

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [74]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
b[[0, 2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [77]:
b[[0, 2], [2, 3]]

array([ 2, 11])

In [78]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [80]:
b = np.arange(10, 14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [81]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [82]:
np.hstack((a, b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [83]:
np.concatenate((a, b), 0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [84]:
np.concatenate((a, b), 1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [91]:
a = np.arange(12).reshape(4, 3)
b = np.arange(10, 130, 10).reshape(4, 3)

In [92]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [93]:
b

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [94]:
c = np.stack((a, b), 0)

In [95]:
c.shape

(2, 4, 3)

In [96]:
c

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]]])

In [98]:
d = np.stack((a, b), 1)

In [99]:
d

array([[[  0,   1,   2],
        [ 10,  20,  30]],

       [[  3,   4,   5],
        [ 40,  50,  60]],

       [[  6,   7,   8],
        [ 70,  80,  90]],

       [[  9,  10,  11],
        [100, 110, 120]]])

In [100]:
e = np.stack((a, b), 2)

In [101]:
e.shape

(4, 3, 2)

In [102]:
e

array([[[  0,  10],
        [  1,  20],
        [  2,  30]],

       [[  3,  40],
        [  4,  50],
        [  5,  60]],

       [[  6,  70],
        [  7,  80],
        [  8,  90]],

       [[  9, 100],
        [ 10, 110],
        [ 11, 120]]])

In [103]:
ee = np.stack((a, b), -1)

In [104]:
ee.shape

(4, 3, 2)

In [105]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [106]:
np.hsplit(a, 3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [107]:
np.hsplit(a, [3, 6])

[array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [108]:
np.hsplit(a, [3, 6, 9])

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [109]:
np.split(a, 3, 0)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [110]:
np.split(a, [3, 6, 9], 0)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [111]:
b = np.arange(12).reshape(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [112]:
np.vsplit(b, 2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [113]:
np.split(b, 2, 0)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [114]:
np.hsplit(b, [1])

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [115]:
np.split(b, [1], 1)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])]

In [116]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [117]:
np.where(a>15)

(array([6, 7, 8, 9], dtype=int64),)

In [118]:
np.where(a > 15, 1, 0)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [119]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [121]:
np.where(a>15, 99, a)

array([10, 11, 12, 13, 14, 15, 99, 99, 99, 99])

In [122]:
np.where(a>15, a, 0)

array([ 0,  0,  0,  0,  0,  0, 16, 17, 18, 19])

In [123]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
coords = np.where(b > 6)

In [125]:
coords

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [126]:
np.stack( (coords[0], coords[1]), -1)

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]], dtype=int64)

In [127]:
z = np.array([0, 1, 2, 0, 1, 2])
np.nonzero(z)

(array([1, 2, 4, 5], dtype=int64),)

In [128]:
zz = np.array([[0, 1, 2], [1, 2, 0], [2, 0, 1]])
zz

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [129]:
coords = np.nonzero(zz)
coords

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 0, 2], dtype=int64))

In [130]:
np.stack( (coords[0], coords[1]), -1)

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]], dtype=int64)

In [131]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [132]:
np.nonzero(a>15)

(array([6, 7, 8, 9], dtype=int64),)

In [133]:
np.where(a > 15)

(array([6, 7, 8, 9], dtype=int64),)

In [134]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
np.nonzero(b>6)

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [136]:
np.where(b>6)

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [137]:
t = np.array([True, True, True])

In [138]:
np.all(t)

True

In [140]:
t[1] = False

In [141]:
np.all(t)

False

In [145]:
tt = np.array([[True, True], [False, True], [True, True]])

In [146]:
tt

array([[ True,  True],
       [False,  True],
       [ True,  True]])

In [147]:
np.all(tt, 0)

array([False,  True])

In [148]:
np.all(tt, 1)

array([ True, False,  True])

In [149]:
a = np.arange(10)
b = np.arange(10)

In [150]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [154]:
np.all(a==b)

True

In [155]:
b[5] = -1

In [156]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
b

array([ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9])

In [158]:
np.all(a==b)

False

In [159]:
np.where(a==b)

(array([0, 1, 2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [160]:
np.where(a!=b)

(array([5], dtype=int64),)

In [161]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
np.sum(a)

66

In [163]:
np.sum(a, 0)

array([12, 15, 18, 21])

In [164]:
np.sum(a, 1)

array([ 6, 22, 38])

In [165]:
np.mean(a)

5.5

In [166]:
np.mean(a, 0)

array([4., 5., 6., 7.])

In [167]:
np.mean(a, 1)

array([1.5, 5.5, 9.5])

In [168]:
np.amin(a)

0

In [169]:
np.amin(a, 0)

array([0, 1, 2, 3])

In [170]:
np.amin(a, 1)

array([0, 4, 8])

In [171]:
np.amax(a)

11

In [172]:
np.amax(a, 0)

array([ 8,  9, 10, 11])

In [173]:
np.amax(a, 1)

array([ 3,  7, 11])

In [176]:
import cv2
import numpy as np
img = np.zeros((120, 120), dtype = np.uint8)
img[25:35, :] = 45
img[55:65, :] = 115
img[85:95, :] = 160
img[:, 35:45] = 205
img[:, 75:85] = 255
cv2.imshow('Gray', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [177]:
import cv2
import numpy as np

img = np.zeros((120, 120, 3), dtype=np.uint8)
img[25:35, :] = [255, 0, 0]
img[55:65, :] = [0, 255, 0]
img[85:95, :] = [0, 0, 255]
img[:, 35:45] = [255, 255, 0]
img[:, 75:85] = [255, 0, 255]
cv2.imshow('BGR', img)
cv2.waitKey(0)
cv2.destroyAllWindows()